config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reqs do
    member do
      get 'start', to: "reqs#start"
    end
  end
  resources :candidates do
      resources :chatrooms do
        resources :messages, only: :create
      end
    member do
       get 'map', to: "candidates#map"
       get 'profile', to: "candidates#profile"
       get 'tchat', to: "candidates#tchat"
      end
    member do
      post 'discover', to: "candidates#discover"
      post 'select', to: "candidates#select"
      post 'save', to: "candidates#save"
      post 'archive', to: "candidates#archive"
      post 'export', to: "candidates#export"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :challenges
  has_many :jobs
  has_many :chatrooms
  belongs_to :country
  #belongs_to :tech_hub
  has_one_attached :photo
  has_one_attached :map
end

app/models/candidate_stack.rb
class CandidateStack < ApplicationRecord
 #belongs_to :candidate
  #belongs_to :stack
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :candidate
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :candidate
end

app/models/company.rb
class Company < ApplicationRecord
  has_one_attached :photo
  #has_one_attached :video
end

app/models/competitor.rb
class Competitor < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :candidates
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :candidate
  has_one_attached :photo
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
end

app/models/mission.rb
class Mission < ApplicationRecord
  #belongs_to :req
end

app/models/req.rb
class Req < ApplicationRecord
  #has_many :missions
  #has_many :req_stacks
  #has_many :users
  has_one_attached :photo
  has_many :tech_hubs
end

app/models/req_stack.rb
class ReqStack < ApplicationRecord
  #belongs_to :req
end

app/models/stack.rb
class Stack < ApplicationRecord
  #has_many :req_stacks
  #has_many :candidate_stacks
  #has_many :candidates, through: :candidate_stacks

end

app/models/tech_hub.rb
class TechHub < ApplicationRecord
  #has_many :candidates
  #has_many :countries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #belongs_to :req
  has_one_attached :photo
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def index
    @candidates = Candidate.all
    @new_candidates = Candidate.where(status: "New")
  end

  def profile
    @tech_hubs = TechHub.all
    @candidate = Candidate.find(params[:id])
    @new_candidates = Candidate.where(status: "New")

    @reqs = Req.all
    @candidates = Candidate.all
    @chatroom = Chatroom.first
  end

  def map
    @tech_hubs = TechHub.all
    @users = User.all
    @candidate = Candidate.find(params[:id])
    @new_candidates = Candidate.where(status: "New")

    @reqs = Req.all
    @candidates = Candidate.all
    @chatroom = Chatroom.first
  end

  def discover
    @candidates = Candidate.all
    @candidate = Candidate.find(params[:id])
    @candidate.status = "autre"
       @candidates.each do |candidate|
        candidate.selected = false
        candidate.save
      end
    @candidate.selected = true
    @candidate.save
    redirect_to map_candidate_path(@candidate)
  end

  def select
    @candidates = Candidate.all
      @candidates.each do |candidate|
        candidate.selected = false
        candidate.save
      end
    @candidate = Candidate.find(params[:id])
    @candidate.selected = true
    @candidate.save
    redirect_to map_candidate_path(@candidate) #tab: "notification"
  end

  def new
    @tech_hubs = TechHub.all
    @req = Req.new
  end

  def save
    @candidate = Candidate.find(params[:id])
    @next_candidate = Candidate.find(params[:id].next)
    @candidate.status = "saved"
    @next_candidate.selected = true
    @candidate.selected = false
    @candidate.save
    @next_candidate.save
    redirect_to map_candidate_path(@next_candidate)
  end


  def archive
    @candidate = Candidate.find(params[:id])
    @next_candidate = Candidate.find(params[:id].next)
    @candidate.status = "archived"
    @next_candidate.selected = true
    @candidate.selected = false
    @candidate.save
    @next_candidate.save
    redirect_to map_candidate_path(@next_candidate)
  end

  def export
    @candidate = Candidate.find(params[:id])
    @next_candidate = Candidate.find(params[:id].next)
    @candidate.status = "Current"
    @next_candidate.selected = true
    @candidate.selected = false
    @candidate.save
    @next_candidate.save
    redirect_to map_candidate_path(@next_candidate)
  end



  #def tchat
    #@chatroom = Chatroom.last


    #@candidate = Candidate.find(params[:id])
    #@reqs = Req.all
    #@candidates = Candidate.all
    #@message = Message.new
  #end
  end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def show
    @tech_hubs = TechHub.all
    @users = User.all
    @candidate = Candidate.find(params[:candidate_id])
    @users = User.all
    @chatroom = @candidate.chatrooms.first
    @messages = @chatroom.messages

    @reqs = Req.all
    @candidates = Candidate.all
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @candidate = Candidate.find(params[:candidate_id])
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom_id = @chatroom.id
    @message.user_id = User.first.id
    @candidate.status = "Current"
    @candidate.save!
    if @message.save
      redirect_to candidate_chatroom_path(@candidate, @chatroom)
    else
      p "fail"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @reqs = Req.all
    @candidates = Candidate.all

  end


end

app/controllers/reqs_controller.rb
class ReqsController < ApplicationController
      def index
        @reqs = Req.all
        @candidates = Candidate.all
      end

      def new
        @candidates = Candidate.all
        @users = User.all
        @reqs = Req.all
        @tech_hubs = TechHub.all
        @companies = Company.all
      end

      def show
        @users = User.all
        @reqs = Req.all
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/map.html.erb
<body>
  <div class="row">
      <div class="col-2" style="background-color: #090131">
        <div style="head">
          <%= cl_image_tag("Group_73_ekm9tm", width: 124, height: 45, style: 'margin-top: 26px; margin-left: 20px;') %>
        </div>
        <div class="req_header">
          <button> <%= link_to "+ Open new Req", new_req_path, style: "color: white; text-decoration: none;" %></button>
        </div>
              <div>
        <div class="candidate_nav" style="margin-left: 10px;">
        <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" style="color: white" id="pills-contact-tab" data-toggle="pill" href="#pills-new" role="tab" aria-controls="pills-home" aria-selected="true">Opened (4) </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" id="pills-contact-tab" data-toggle="pill" href="#pills-current" role="tab" aria-controls="pills-profile" aria-selected="false">To review (0)</a>
        </li>
      </ul>
    </div>
<%= cl_image_tag("Line_1_nwlm9y",
          width: 200, height: 1, style: 'margin-left: 20px;') %>
        <%= render template: "reqs/home" %>
      </div>
      </div>
      <div class="col-3" style="background-color: #FFFFFF">
        <%= render template: "candidates/home" %>
      </div>
      <div class="col-7">
      <div class="row">
        <div class="col-6 mapp">
          <%= cl_image_tag @candidate.map.key, height:750, width: 395 %>
        </div>
        <div class="col-6 profile">
          <%= render template: "candidates/profile2" %>
        </div>
      </div>

      </div>
  </div>
</body>

<style>

.col {
  padding-top: -20px !important;
}

.block2 {
  display: flex;
  justify-content: flex-start;
}


.mapp {
  height: 100vh;
}

.profile {
  background-color: white;
  padding-top: -10px;
  height: 100vh;
}


  #mapy {
    color: black;
  }

  #mappy {
    color: black;
  }

  .selection {
  background-color: #EDEAFA;
}
</style>

app/views/candidates/profile2.html.erb
<div class="propro">
  <div class="id-info">
    <div class="profile-info">
                  <div>
                    <%= cl_image_tag @candidate.photo.key, width: 60, height: 60 %>
                  </div>
                <div class="info-pro">
                    <h5><%= @candidate.first_name + " " + @candidate.last_name %></h5>
                    <p><%= @candidate.job %> (<%= @candidate.job_status %>) </p>
                    <p id="loc"><%= @candidate.location + " " %><i class="fab fa-github"></i><%= + " " %><i class="fab fa-linkedin-in"></i></p>
                </div>
      </div>
  </div>

<div class="alert alert-success collapse" role="alert" id="alert-success">
  <h5><%= @candidate.first_name + " " + @candidate.last_name %> is in your pipeline 🎉</h5>
  <p>Candidate replies in average in XX days. You can follow the conversation in your ATS </p>
</div>



  <div class="choices">
    <button1 type="button" class="choice" data-toggle="modal" data-target="#exampleModalCenter">
      Export to ATS <i class="fas fa-paper-plane"></i>
    </button1>
    <%= link_to save_candidate_path(@candidate), method: :post, class: 'choice' ,id: 'dis' do %> Share <i class="fas fa-link"></i><% end  %>
    <%= link_to archive_candidate_path(@candidate), method: :post, class: 'choice' ,id: 'dis' do %> Archive <i class="fas fa-archive"></i><% end %>
  </div>
  <div class="profile-nav">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link active" id="pills-contact-tab" data-toggle="pill" href="#pills-location" role="tab" aria-controls="pills-home" aria-selected="true">Location</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-skills" role="tab" aria-controls="pills-profile" aria-selected="false">Skills</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-expectations" role="tab" aria-controls="pills-contact" aria-selected="false">Expectations</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-background" role="tab" aria-controls="pills-contact" aria-selected="false">Background</a>
    </li>
  </ul>
  <%= cl_image_tag("Line_6_u4e9nl", width: 280, style: 'margin-left: 15px') %>
  </div>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-location" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="loca">
        <p>Timezone : <%= @candidate.timezone %></p>
        <p><b><%= @candidate.overlap %> overlap</b> with your team </p>
        <div class="team-overlap">
          <%= cl_image_tag @users[1].photo.key, height: 22, width: 22 %>
          <div style="margin-left: 10px">
            <p><b><%= rand(6..9) %> </b> hours with <%= @users[1].first_name %></p>
          </div>
        </div>
        <div class="team-overlap">
          <%= cl_image_tag @users[2].photo.key, height: 22, width: 22 %>
          <div style="margin-left: 10px">
            <p><b><%= rand(6..9) %></b> hours with <%= @users[2].first_name %></p>
          </div>
        </div>
        <div class="team-overlap">
          <div>
           🏠
          </div>
          <p style="margin-top: 4px; margin-left: 10px;"><b><%= rand(6..9) %></b> hours with HQ </p>
        </div>
      </div>
        <%= cl_image_tag("Line_6_u4e9nl", width: 280, style: 'margin-left: 15px') %>
      <div class="loca">
        <h5 style="font-size: 15px">Compensation</h5>
        <p>💵 Expected : <b> $ <%= @candidate.expected_wage %> K </b><small>(- <%= rand(1..15)%> % of your global floor)</small></p>
        <p>📏 Area median : <%= @candidate.area_median %> </p>
        <p>🗓 Notice period : <%= @candidate.notice_period %> </p>
      </div>
        <%= cl_image_tag("Line_6_u4e9nl", width: 280, style: 'margin-left: 15px') %>
      <div class="loca">
        <h5 style="font-size: 15px">Benefits</h5>
        <p>🚑 <%= @candidate.healthcare %><small>(average cost $2K month)</small></p>
        <p>👴 <%= @candidate.other_benefits %> </p>
      <%= cl_image_tag("Line_6_u4e9nl", width: 280, style: 'margin-left: 15px') %>
      </div>

    </div>
    <div class="tab-pane fade" id="pills-skills" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="staks">
            <% @candidate.languages.each do |language | %>
                <div class="stack">
                  <p><%= language %></p>
                </div>
              <% end  %>
            </div>
                        <div class="staks">
                        <% @candidate.tools.each do |tool| %>
                        <div class="stack" style="background-color: #EDEAFA">
                        <p style="color: black"><%= tool %></p>
                      </div>
                    <% end  %>
                </div>

      <div class="loca">
        <h5 style="font-size: 15px; padding-top: 30px">Challenges</h5>
        <% @candidate.challenges.each_with_index do | challenge, index | %>
          <p><%= index + 1 %> - <%= challenge.description %></p>
          <%= cl_image_tag("Line_6_u4e9nl", width: 280, style: 'margin-left: 15px') %>
        <% end  %>
    </div>
    <div class="loca">
      <h5 style="font-size: 15px; padding-top: 30px">Soft skills </h5>
      <p> <i class="fas fa-user-friends"></i>Worked with : <%= @candidate.softskills %></p>
      <p><i class="fas fa-tasks"></i> <%= @candidate.practice %></p>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-expectations" role="tabpanel" aria-labelledby="pills-home-tab">
    <div class="loca">
      <h5 style="font-size: 15px; padding-top: 30px">Next technical steps</h5>
      <p> <%= @candidate.next_steps %></p>
      <%= cl_image_tag("Line_6_u4e9nl", width: 280, style: 'margin-left: 15px') %>
      <p style="color: #777581">Stacks and tools to explore</p>
    </div>
    <%= cl_image_tag("Line_6_u4e9nl", width: 280, style: 'margin-left: 15px') %>
    <div class="loca">
      <h5 style="font-size: 15px; padding-top: 30px">Next career steps</h5>
      <p> <%= @candidate.next_job %></p>
    </div>
  </div>
    <div class="tab-pane fade" id="pills-background" role="tabpanel" aria-labelledby="pills-home-tab">
        <div class="loca">
          <h5 style="font-size: 15px; padding-top: 30px">Work experience</h5>
          <% @candidate.jobs.each do | job | %>
            <div class="fomer-job" style="
      display: flex;
      justify-content: flex-start;">
              <div>
                <%= cl_image_tag job.photo.key, height: 50, width: 50, crop: :fit %>
              </div>
              <div class="job-desc">
                <p><b> <%= job.company_name %></b></p>
                <p> <%= job.years %></p>
                <p><%= job.title %></p>
              </div>
            </div>
            <%= cl_image_tag("Line_6_u4e9nl", width: 280, style: 'margin-left: 15px') %>
          <% end  %>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="mod-title">
        <h5 class="modal-title" id="exampleModalLongTitle">Send a message <br> to <%= @candidate.first_name + " " + @candidate.last_name  %> </h5>
          <p>Start a conversation in order to add  <%= @candidate.first_name + " " %>to your ATS</p>
      <div style="margin-top: 5px">
      <%= cl_image_tag @users.first.photo.key, height: 35, width: 35, style: "z-index: 1" %>
      <%= cl_image_tag @candidate.photo.key, height: 35, width: 35, style: "margin-left: -10px;" %>
    </div>
      </div>

      <div class="modal-body">
        <textarea id="description" placeholder="Type a relevant message to <%= @candidate.first_name %> "></textarea>
      <hr>
        <p>Add internal feedback note in Lever </p>
        <textarea id="text2" placeholder="Tag @team members and add comments directly in Lever"></textarea>

      <div class="mod-footer">
      <button1 type="button" class="choice" id='dis' data-dismiss="modal">Cancel </button1>
      <%= link_to export_candidate_path(@candidate), method: :post do %>
            <button1 type="button" class="choice" data-dismiss="modal" id="starting">
              Start conversation <i class="fas fa-paper-plane"></i>
            </button1>
      <% end %>
      </div>
      </div>
    </div>
  </div>
</div>


<style>

.alert {
  text-align: center;
  margin-right: 450px;
  margin-bottom: 700px;
}

.alert p {
  font-size: 10px;
}

.mod-footer {
  margin-top: 10px;
  text-align: center;
}


.mod-title {
  text-align: center;
}

textarea {
  padding: 10px;
  border: none;
  outline: none;
  font-size: 10px;
  width: 98%;
  height: 150px;
  background-color: #F0F0F1;
}

#text2 {
  border: none;
  outline: none;
  font-size: 10px;
  width: 98%;
  height: 60px;
  background-color: #F0F0F1;
}

.modal-content {
  border-radius: 10px;
}

.modal-content {
  padding-top: 60px;
  padding-bottom: 60px;
  padding-left: 30px;
  padding-right: 30px;

}

.modal p {
  font-size: 10px;
}

p {
  color: #090131;
}

h5 {
  color: #090131;
}


.job-desc {
  margin-left: 10px;
  line-height: 5px;
}

.former-job {
  display: flex;
  justify-content: flex-start !important;
}


.staks {
  display: flex;
  justify-content: flex-start;
}

.stack {
  margin-top: 5px;
  margin-left: 6px;
  background-color: #090131;
  display: block;
  text-align: center;
  vertical-align: middle;
  border-radius: 10px;
  width: 100px;
  height: 30px;
  line-height: 30px;
  p {
    font-size: 10px;
    color: white;
  }
}

small {
  color: #777581;
  font-size: 8px;
  margin-left: 0px !important;
}


.team-overlap {
  display: flex;
  justify-content: flex-start;
}

.loca {
  margin-left: 15px;
}

.tab-pane p {
  font-size: 10px
}

.tab-pane {
  padding-right: 20px;
  padding-left: 10px;
}

#pills-location p {
  line-height: 9px;
}


.profile-nav {
  font-size: 10px;
  margin-top: 15px;
  margin-bottom: 0px ;
  padding-left: 10px;
}

#pills-contact-tab {
  margin-right: 0px;
}

.choices {
  padding-left: 25px;
}

.choice {
  color: white;
  padding: 10px;
  background-color: #4175FE;
  border-radius: 5px;
  font-size: 10px;
  margin-right: 10px;
}

.choice:hover {
  background-color: blue;
  color: white;
  text-decoration: none;
}

#dis {
  background-color: #F0F0F1;
  color: #090131;
}

#dis:hover{
  background-color: blue;
  color: white;
  text-decoration: none;
}

.info-pro p {
  font-size: 12px;
  margin-bottom: 9px !important;
  color: #777581;
}

#loc {
  color: #090131;
}

.info-pro h5 {
  font-size: 20px;
  color: #090131;
}

.id-info {
  margin-left: 10px;
}

.show {
  display: block i !important;
}

</style>

<script>
  const starting = document.getElementById("starting");
const alert1 = document.getElementById("alert-success");
  starting.addEventListener("click", (event) => {
    alert1.classList.toggle("show");
  });

</script>

app/views/reqs/home.html.erb
<div class="req_box">
   <p><i class="fas fa-user fa-fw"></i><%= @reqs.first.title %></p>
</div>

  <% @reqs.drop(1).each do |req| %>
  <div class="req_box1">
   <p><i class="fas fa-user fa-fw"></i><%= req.title %></p>
   </div>
  <% end %>

app/views/reqs/show.html.erb
<div class="row">
    <div class="col-2" style="background-color: #090131">
      <div class="head">
        <%= cl_image_tag("Group_73_ekm9tm", width: 124, height: 45, style: 'margin-top: 26px; margin-left: 20px;') %>
      </div>
    </div>
    <div class="col-10">
      <div class="ats-head">
        <h4>Connect your ATS </h4>
        <p>Choose your ATS to start using Magellan</p>
      </div>
    <div class="atss">
      <div class="ats" data-toggle="modal" data-target="#exampleModalCenter">
        <div class="logoo">
          <%= cl_image_tag("lever_logo_1_bt5iu5", width: 140, height: 40) %>
        </div>
        <div class="desc-ats">
          <h5>Lever</h5>
          <p>Export profiles from Magellan to Lever in one click </p>
        </div>
      </div>

      <div class="ats" data-toggle="modal" data-target="#exampleModalCenter">
        <div class="logoo">
          <%= cl_image_tag("2197153_1_x3mvwg", width: 40, height: 40) %>
        </div>
        <div class="desc-ats">
          <h5>Workable</h5>
          <p>Export profiles from Magellan to Workable in one click </p>
        </div>
      </div>

      <div class="ats" data-toggle="modal" data-target="#exampleModalCenter">
        <div class="logoo">
         <%= cl_image_tag("greenhouse-logo-freelogovectors.net__hmzdi4", width: 15, height: 35) %>
        </div>
        <div class="desc-ats">
          <h5>Greenhouse</h5>
          <p>Export profiles from Magellan to Greenhouse in one click </p>
        </div>
      </div>

      <div class="ats" data-toggle="modal" data-target="#exampleModalCenter">
        <div class="logoo">
          <%= cl_image_tag("recruitee", width: 130, height: 35) %>
        </div>
        <div class="desc-ats">
          <h5>Recruitee</h5>
          <p>Export profiles from Magellan to Recruitee in one click </p>
        </div>
      </div>

      <div class="ats" data-toggle="modal" data-target="#exampleModalCenter">
        <div class="logoo">
          <%= cl_image_tag("teamtailor_eb16dq", width: 130, height: 33) %>
        </div>
        <div class="desc-ats">
          <h5>Teamtailor</h5>
          <p>Export profiles from Magellan to Teamtailor in one click </p>
        </div>
      </div>
    </div>
    </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="mod-title">
        <h4 class="modal-title" id="exampleModalLongTitle">Import your Reqs </h4>
          <p style="margin-top: 5px">Select by posting owner <i class="fas fa-chevron-down"></i></p>
      <div class="guy" style="margin-top: 5px">
        <div class="user-select-photo">
          <%= cl_image_tag @users.first.photo.key, height: 35, width: 35 %>
        </div>
        <div class="user-info">
        <p><%= @users.first.first_name %> <%= @users.first.last_name %> </p>
        <p style="margin-top: -15px"><%= @users.first.job %><br>
        </div>
    </div>
      </div>

      <div class="modal-body">

        <% @reqs.each do |req| %>
         <%= cl_image_tag("Line_81_vjrh7z", width: 400, height: 1) %>
         <div class="reqi">
            <%= cl_image_tag("check-square-solid_1_1_rtbyof", width: 10, height: 11) %><p id="tit"><%= req.title %></p>
         </div>
        <% end  %>

      <div class="mod-footer">
            <%= link_to new_req_path do %>
            <button1 type="button" class="choice" id="starting">
              Import 4 Reqs
            </button1>
          <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

<style>

.ats:hover {
    background-color: #EDEAFA;
    cursor: pointer;
}

.user-info {
  margin-left: 10px;
}

.guy {
  display: flex;
  justify-content: flex-start;
}

.choice {
  color: white;
  padding: 10px;
  background-color: #4175FE;
  border-radius: 5px;
  font-size: 10px;
  margin-right: 10px;
  outline: none;
}

.choice:hove {
  outline: none;
  text-decoration: none;
}

#tit {
  margin-left: 10px;
}

.reqi {
  display: flex;
  justify-content: flex-start;
}


h4 {
  color: #777581;
  padding-top: 20px;
}


#exampleModalLongTitle {
    color: #090131;

}

h5 {
  color: #090131;
}

p {
  color: #090131;
  font-size: 10px;
}

.ats-head {
  margin-left: 20px;
}

.ats {
  padding: 25px;
  background-color: white;
  width: 300px;
  height: 200px;
  border-radius: 10px;
  margin-right: 20px;
  margin-top: 20px;
}

.ats:hover {
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
}

.desc-ats {
  margin-top: 20px;
}


.atss {
  display: flex;
  flex-wrap: wrap;
  align-items: start;
  margin-left: 20px;
}


.mod-footer {
  margin-top: 10px;
  text-align: center;
}


textarea {
  padding: 10px;
  border: none;
  outline: none;
  font-size: 10px;
  width: 98%;
  height: 150px;
  background-color: #F0F0F1;
}

#text2 {
  border: none;
  outline: none;
  font-size: 10px;
  width: 98%;
  height: 60px;
  background-color: #F0F0F1;
}

.modal-content {
  border-radius: 10px;
}

.modal-content {
  padding-top: 60px;
  padding-bottom: 60px;
  padding-left: 50px;
  padding-right: 50px;

}

.modal p {
  font-size: 10px;
}


</style>